export const services = [
  {
    id: 1,
    img: '../images/car.png',
    title: 'importing',
    info: 'To allow clients to conviently import cars worldwide through the most trusted dealership in the country.',
  },
  {
    id: 2,
    img: '../images/car-fork.png',
    title: 'maintenance',
    info: 'We have a service offering Motor vehicle maintenance services such as respray and parts upgrades. ',
  },
  {
    id: 3,
    img: '../images/lorry.png',
    title: 'trade-ins',
    info: 'To allow clients to conviently upgrade from current vehicle to a newer and freasher unit. Trade-ins save money.',
  },
]
export const cars = [
  {
    id: 1,
    name: 'Yellow Chevy Camaro',
    price: 'KSH 6,500,000',
    year: 2019,
    tank: '7000 CC',
    img: '../images/cheveron.png',
    logo: '../images/cheveron-logo.png',
    category: 'new arrivals',
  },
  {
    id: 2,
    name: 'Matte Black Lamborghini',
    price: 'KSH 76,200,000',
    year: 2020,
    tank: '6498 CC',
    img: '../images/lambogini.png',
    logo: '../images/lambo-logo.png',
    category: 'new arrivals',
  },
  {
    id: 3,
    name: 'BMW M5 Frozen White',
    price: 'KSH 13,670,000',
    year: 2013,
    tank: '4395 CC',
    img: '../images/Bmw.png',
    logo: '../images/bmw-logo.png',
    category: 'new arrivals',
  },
  {
    id: 4,
    name: 'Green Bentley Continental',
    price: 'KSH 90,200,000',
    year: 2021,
    tank: '5498 CC',
    img: '../images/benly.jpg',
    logo: '../images/bent-logo.png',
    category: 'used cars',
  },
  {
    id: 5,
    name: 'Ford Ranger Wildtrak Silver',
    price: 'KSH 46,200,000',
    year: 2018,
    tank: '7098 CC',
    img: '../images/ford-hilux.jpg',
    logo: '../images/ford.png',
    category: 'Pre-Owned',
  },
  {
    id: 6,
    name: 'Mercedes Benz Yellow',
    price: 'KSH 95,200,000',
    year: 2021,
    tank: '7028 CC',
    img: '../images/mercedes.jpg',
    logo: '../images/benz-log.jpg',
    category: 'certified vehicles',
  },
  {
    id: 7,
    name: 'Ford Ranger Red',
    price: 'KSH 43,200,000',
    year: 2018,
    tank: '7098 CC',
    img: '../images/ford-hilux.jpg',
    logo: '../images/ford-logo.png',
    category: 'used cars',
  },
  {
    id: 8,
    name: 'Mercedes Benz Green',
    price: 'KSH 95,200,000',
    year: 2020,
    tank: '6828 CC',
    img: '../images/green-benz.jpg',
    logo: '../images/benz-logo.jpg',
    category: 'pre-Owned cars',
  },
  {
    id: 9,
    name: 'Bugatti',
    price: 'KSH 110,200,000',
    year: 2020,
    tank: '700 CC',
    img: '../images/buggati.jpg',
    logo: '../images/bugatti-logo.png',
    category: 'pre-Owned cars',
  },
  {
    id: 10,
    name: 'Lexus Lx570',
    price: 'KSH 95,200,000',
    year: 2021,
    tank: '7008 CC',
    img: '../images/lexus-3.jpg',
    logo: '../images/lexus-logo.jpg.jpg',
    category: 'certified vehicles',
  },
  {
    id: 11,
    name: 'Lexus Lx590',
    price: 'KSH 75,200,000',
    year: 2022,
    tank: '6508 CC',
    img: '../images/lexus.jpg',
    logo: '../images/lexus-logo.jpg',
    category: 'certified vehicles',
  },
  {
    id: 12,
    name: 'Honda Accord',
    price: 'KSH 95,200,000',
    year: 2021,
    tank: '7008 CC',
    img: '../images/honda.jpg',
    logo: '../images/honda-logo.jpg.jpg',
    category: 'certified vehicles',
  },
]
